"""
Cloud Infrastructure Silicon & PQC Readiness Knowledge Matrix.

Authoritative mappings of AWS, Azure, and GCP compute shapes, processor families,
SIMD vector extensions, CloudHSM generations, and Load Balancer TLS policies
against Post-Quantum Cryptography standards (NIST FIPS 203/204/205).
"""

from typing import Any, Dict

CLOUD_SILICON_MATRIX: Dict[str, Dict[str, Any]] = {
    # ==================== AWS EC2 INSTANCES ====================
    "t2.micro": {
        "provider": "AWS",
        "category": "Burstable General Purpose",
        "cpu_family": "Intel Xeon E5-2676 v3 (Haswell)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": False,
        "neon": False,
        "burstable": True,
        "pqc_status": "UPGRADE_REQUIRED",
        "performance_penalty": 5.4,
        "recommendation": "Migrate to t4g.micro (AWS Graviton2 ARM NEON). 20% cheaper, eliminates burstable CPU throttling on PQC handshakes, and provides 4.2x faster lattice operations.",
        "upgrade_target": "t4g.micro",
        "cost_delta_pct": -20.0,
    },
    "t2.medium": {
        "provider": "AWS",
        "category": "Burstable General Purpose",
        "cpu_family": "Intel Xeon E5-2676 v3 (Haswell)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": False,
        "neon": False,
        "burstable": True,
        "pqc_status": "UPGRADE_REQUIRED",
        "performance_penalty": 5.4,
        "recommendation": "Migrate to t4g.medium (AWS Graviton2 ARM NEON). Eliminates CPU credit starvation during TLS 1.3 ML-KEM handshakes.",
        "upgrade_target": "t4g.medium",
        "cost_delta_pct": -20.0,
    },
    "t3.medium": {
        "provider": "AWS",
        "category": "Burstable General Purpose",
        "cpu_family": "Intel Xeon Platinum 8175M (Skylake) / 8259CL (Cascade Lake)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": True,
        "neon": False,
        "burstable": True,
        "pqc_status": "UPGRADE_RECOMMENDED",
        "performance_penalty": 1.4,
        "recommendation": "Supports AVX-512 for NTT acceleration, but burstable CPU credits create latency spikes under high TLS handshake load. Upgrade to c6i.large or t4g.medium.",
        "upgrade_target": "t4g.medium",
        "cost_delta_pct": -20.0,
    },
    "t4g.medium": {
        "provider": "AWS",
        "category": "ARM Burstable General Purpose",
        "cpu_family": "AWS Graviton2 (ARM Neoverse N1)",
        "arch": "aarch64",
        "avx2": False,
        "avx512": False,
        "neon": True,
        "burstable": True,
        "pqc_status": "PQC_READY",
        "performance_penalty": 1.1,
        "recommendation": "Native ARM NEON SIMD vectorization with predictable baseline. Well-suited for cost-effective PQC web endpoints.",
        "upgrade_target": "Maintain",
        "cost_delta_pct": 0.0,
    },
    "m4.xlarge": {
        "provider": "AWS",
        "category": "Legacy General Purpose",
        "cpu_family": "Intel Xeon E5-2686 v4 (Broadwell)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": False,
        "neon": False,
        "burstable": False,
        "pqc_status": "UPGRADE_RECOMMENDED",
        "performance_penalty": 2.8,
        "recommendation": "Legacy Broadwell core lacks AVX-512 NTT acceleration. Upgrade to m6i.xlarge (Intel Ice Lake) for 2.8x faster handshakes and lower latency.",
        "upgrade_target": "m6i.xlarge",
        "cost_delta_pct": -7.0,
    },
    "c5.xlarge": {
        "provider": "AWS",
        "category": "Compute Optimized",
        "cpu_family": "Intel Xeon Platinum 8124M (Skylake-SP)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": True,
        "neon": False,
        "burstable": False,
        "pqc_status": "PQC_READY",
        "performance_penalty": 1.0,
        "recommendation": "Dual AVX-512 FMA vector units deliver optimal polynomial multiplication for ML-KEM-768 key encapsulation.",
        "upgrade_target": "Maintain",
        "cost_delta_pct": 0.0,
    },
    "c6i.xlarge": {
        "provider": "AWS",
        "category": "Compute Optimized",
        "cpu_family": "Intel Xeon Platinum 8375C (Ice Lake)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": True,
        "neon": False,
        "burstable": False,
        "pqc_status": "PQC_READY",
        "performance_penalty": 0.95,
        "recommendation": "State-of-the-art Intel Ice Lake core with AVX-512 VNNI and VAES. Tier-1 choice for high-throughput Post-Quantum TLS.",
        "upgrade_target": "Maintain",
        "cost_delta_pct": 0.0,
    },
    "c7g.xlarge": {
        "provider": "AWS",
        "category": "ARM Compute Optimized",
        "cpu_family": "AWS Graviton3 (ARM Neoverse V1)",
        "arch": "aarch64",
        "avx2": False,
        "avx512": False,
        "neon": True,
        "burstable": False,
        "pqc_status": "PQC_READY",
        "performance_penalty": 0.90,
        "recommendation": "Features dual 256-bit SVE (Scalable Vector Extension) and NEON. Highest energy-efficiency and lowest per-handshake latency for PQC.",
        "upgrade_target": "Maintain",
        "cost_delta_pct": 0.0,
    },

    # ==================== AZURE VM SHAPES ====================
    "Standard_B2s": {
        "provider": "Azure",
        "category": "Burstable General Purpose",
        "cpu_family": "Intel Xeon E5-2673 v3 (Haswell) / v4 (Broadwell)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": False,
        "neon": False,
        "burstable": True,
        "pqc_status": "UPGRADE_REQUIRED",
        "performance_penalty": 4.8,
        "recommendation": "Burstable VM with legacy CPU. Upgrade to Standard_D2s_v5 (Ice Lake) for AVX-512 support.",
        "upgrade_target": "Standard_D2s_v5",
        "cost_delta_pct": 10.0,
    },
    "Standard_D4s_v5": {
        "provider": "Azure",
        "category": "General Purpose",
        "cpu_family": "Intel Xeon Platinum 8370C (Ice Lake)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": True,
        "neon": False,
        "burstable": False,
        "pqc_status": "PQC_READY",
        "performance_penalty": 0.95,
        "recommendation": "Native AVX-512 vector support and accelerated networking. Ready for enterprise FIPS 203/204 workloads.",
        "upgrade_target": "Maintain",
        "cost_delta_pct": 0.0,
    },
    "Standard_D4ps_v5": {
        "provider": "Azure",
        "category": "ARM General Purpose",
        "cpu_family": "Ampere Altra (ARM Neoverse N1)",
        "arch": "aarch64",
        "avx2": False,
        "avx512": False,
        "neon": True,
        "burstable": False,
        "pqc_status": "PQC_READY",
        "performance_penalty": 1.05,
        "recommendation": "Dedicated ARM NEON cores. High efficiency and stable latency for post-quantum workloads.",
        "upgrade_target": "Maintain",
        "cost_delta_pct": 0.0,
    },

    # ==================== GCP COMPUTE SHAPES ====================
    "n1-standard-4": {
        "provider": "GCP",
        "category": "Legacy General Purpose",
        "cpu_family": "Intel Xeon (Sandy Bridge / Ivy Bridge / Haswell)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": False,
        "neon": False,
        "burstable": False,
        "pqc_status": "UPGRADE_REQUIRED",
        "performance_penalty": 5.1,
        "recommendation": "First-generation GCE shape lacks AVX-512. Migrate to n2-standard-4 (Cascade Lake) or c2-standard-4.",
        "upgrade_target": "n2-standard-4",
        "cost_delta_pct": -5.0,
    },
    "n2-standard-4": {
        "provider": "GCP",
        "category": "General Purpose",
        "cpu_family": "Intel Xeon Platinum (Cascade Lake / Ice Lake)",
        "arch": "x86_64",
        "avx2": True,
        "avx512": True,
        "neon": False,
        "burstable": False,
        "pqc_status": "PQC_READY",
        "performance_penalty": 1.0,
        "recommendation": "Full AVX-512 vectorization enabled. Standard enterprise post-quantum recommendation.",
        "upgrade_target": "Maintain",
        "cost_delta_pct": 0.0,
    },
    "t2a-standard-4": {
        "provider": "GCP",
        "category": "ARM General Purpose",
        "cpu_family": "Ampere Altra ARM64",
        "arch": "aarch64",
        "avx2": False,
        "avx512": False,
        "neon": True,
        "burstable": False,
        "pqc_status": "PQC_READY",
        "performance_penalty": 1.05,
        "recommendation": "ARM NEON SIMD vector acceleration. Cost-optimized for microservice API ingress.",
        "upgrade_target": "Maintain",
        "cost_delta_pct": 0.0,
    },
}

CLOUD_MANAGED_SERVICES_MATRIX: Dict[str, Dict[str, Any]] = {
    # AWS CloudHSM
    "aws_cloudhsm_classic": {
        "provider": "AWS",
        "type": "HSM",
        "name": "AWS CloudHSM Classic (SafeNet Luna v5)",
        "pqc_status": "UPGRADE_REQUIRED",
        "fips_level": "FIPS 140-2 Level 3",
        "finding": "Legacy SafeNet hardware. Firmware cannot be upgraded to support NIST FIPS 204 (ML-DSA) key generation.",
        "recommendation": "Migrate keys and applications to AWS CloudHSM v2 (FIPS 140-3 Level 3) cluster.",
    },
    "aws_cloudhsm_v2": {
        "provider": "AWS",
        "type": "HSM",
        "name": "AWS CloudHSM v2 (LiquidSecurity)",
        "pqc_status": "FIRMWARE_UPGRADE_RECOMMENDED",
        "fips_level": "FIPS 140-3 Level 3",
        "finding": "Modern Marvell LiquidSecurity hardware coprocessor. Supports PQC algorithm updates via vendor firmware patch.",
        "recommendation": "Contact AWS Support to apply latest HSM firmware bundle enabling ML-KEM-768 and ML-DSA-65.",
    },

    # Azure Key Vault Managed HSM
    "azure_keyvault_managed_hsm": {
        "provider": "Azure",
        "type": "HSM",
        "name": "Azure Key Vault Managed HSM",
        "pqc_status": "FIRMWARE_UPGRADE_RECOMMENDED",
        "fips_level": "FIPS 140-3 Level 3",
        "finding": "Single-tenant Marvell HSM backing. Currently exposes RSA/ECC; PQC APIs entering preview.",
        "recommendation": "Register for Azure PQC Private Preview for hybrid key wrapping and HSM-backed ML-KEM.",
    },

    # Load Balancer TLS Policies
    "aws_alb_policy_2016_08": {
        "provider": "AWS",
        "type": "LoadBalancer",
        "name": "ELBSecurityPolicy-2016-08",
        "pqc_status": "UPGRADE_REQUIRED",
        "finding": "Legacy security policy allows TLS 1.0/1.1 and obsolete RSA key exchanges. Completely vulnerable to Shor's algorithm.",
        "recommendation": "Upgrade listener policy to ELBSecurityPolicy-TLS13-1-2-Res-2021-06 or enable hybrid PQC policy.",
    },
    "aws_alb_policy_tls13_modern": {
        "provider": "AWS",
        "type": "LoadBalancer",
        "name": "ELBSecurityPolicy-TLS13-1-2-Res-2021-06",
        "pqc_status": "PQC_READY",
        "finding": "Enforces TLS 1.3 with forward secrecy. Ready to negotiate post-quantum hybrid groups (X25519MLKEM768).",
        "recommendation": "Optimal configuration for public web traffic.",
    },
}
