"""
GitHub Issue & Developer Remediation Generator.

Transforms cryptographic vulnerabilities into GitHub issues with
detailed technical context, NIST migration roadmaps, and ready-to-merge code snippets.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import httpx

from app.core.migration.recommender import MigrationRecommender, MigrationAction

logger = logging.getLogger(__name__)


@dataclass
class GitHubIssuePayload:
    """Represents a structured GitHub Issue ready to be published."""
    title: str
    body: str
    labels: List[str] = field(default_factory=list)
    assignees: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "body": self.body,
            "labels": self.labels,
            "assignees": self.assignees,
        }


class GitHubIssueCreator:
    """
    Creates markdown issue templates and communicates with the GitHub REST API.
    """

    @classmethod
    def generate_issue_for_finding(
        cls,
        finding: Any,
        repo_name: Optional[str] = None,
    ) -> GitHubIssuePayload:
        f = finding.__dict__ if hasattr(finding, "__dict__") else finding

        name = f.get("name") or "Cryptographic Finding"
        algo = f.get("algorithm") or "Unknown"
        file_path = f.get("file_path") or "Unknown file"
        line_no = f.get("line_number")
        func_name = f.get("function_name")
        risk_score = f.get("risk_score") or 0.0
        risk_level = f.get("risk_level") or "HIGH"
        sensitivity = f.get("sensitivity") or "UNKNOWN"

        action = MigrationRecommender.recommend_for_finding(finding)

        loc_str = file_path
        if line_no:
            loc_str += f":L{line_no}"
        if func_name:
            loc_str += f" in `{func_name}()`"

        title = f"[PQC-Remediation] Upgrade {algo} to {action.target_algorithm} ({loc_str.split('/')[-1]})"

        checklist_md = "\n".join(f"- [ ] {item}" for item in action.testing_checklist)

        body = f"""### 🛡️ Post-Quantum Security Remediation

A quantum-vulnerable cryptographic implementation was discovered during discovery scanning.

| Property | Details |
| :--- | :--- |
| **Asset Name** | `{name}` |
| **Location** | `{loc_str}` |
| **Current Algorithm** | `{algo}` |
| **Target PQC Standard** | `{action.target_algorithm}` ({action.target_standard}) |
| **Priority** | **{action.priority}** (Risk Score: `{risk_score}/100`) |
| **Data Sensitivity** | `{sensitivity}` |

---

### ⚠️ Vulnerability Context
{action.urgency_reason}

---

### 💻 Recommended Code Remediation
```python
{action.code_remediation_snippet.strip()}
```

---

### 📋 Migration Checklist
{checklist_md}

*Automated issue generated by CipherSight Post-Quantum Discovery Platform.*
"""

        labels = ["security", "post-quantum", "cryptography", action.priority.lower()]

        return GitHubIssuePayload(
            title=title,
            body=body,
            labels=labels,
        )

    @classmethod
    async def publish_issue_to_github(
        cls,
        owner: str,
        repo: str,
        token: str,
        issue: GitHubIssuePayload,
    ) -> Dict[str, Any]:
        """
        Publish the issue directly to the GitHub repository using a personal access token.
        """
        url = f"https://api.github.com/repos/{owner}/{repo}/issues"
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "CipherSight-PQC-Scanner",
        }

        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(url, json=issue.to_dict(), headers=headers)
            if resp.status_code != 201:
                logger.error("GitHub API error: %s %s", resp.status_code, resp.text)
                return {
                    "success": False,
                    "status_code": resp.status_code,
                    "error": resp.text,
                }
            data = resp.json()
            return {
                "success": True,
                "issue_url": data.get("html_url"),
                "issue_number": data.get("number"),
            }
