"""
Cryptographic signatures and detection rules for compiled binary scanning.

Covers:
- Symbol table exports and imports (ELF, PE, Mach-O)
- Cryptographic library API signatures (OpenSSL, liboqs, libsodium, mbedTLS, WolfSSL, Windows BCrypt)
- PQC algorithm identifiers (ML-KEM, ML-DSA, SLH-DSA, Falcon, Kyber, Dilithium)
- Hardcoded algorithm names and version strings
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class BinaryCryptoSignature:
    symbol_or_pattern: str
    name: str
    library: str
    algorithm: str
    algorithm_family: str
    primitive: str          # asymmetric | symmetric | hash | pqc | hybrid | kdf | mac
    usage: str              # key_generation | encryption | digital_signature | hashing | key_exchange
    pqc_status: str         # QUANTUM_SAFE | HYBRID_READY | VULNERABLE | REDUCED_SECURITY_MARGIN | UNKNOWN
    quantum_status: str     # safe | vulnerable | reduced_security_margin | unknown
    base_risk_score: float  # 0 - 100
    risk_level: str         # CRITICAL | HIGH | MEDIUM | LOW | INFO
    vulnerabilities: List[str]
    recommendations: List[str]
    min_confidence: float = 0.90


# Exact symbol name mappings from binary export/import symbol tables
SYMBOL_SIGNATURES: Dict[str, BinaryCryptoSignature] = {
    # ── OpenSSL / LibreSSL / BoringSSL: Asymmetric (Quantum Vulnerable) ─────
    "RSA_generate_key": BinaryCryptoSignature(
        symbol_or_pattern="RSA_generate_key",
        name="OpenSSL RSA Key Generation",
        library="OpenSSL",
        algorithm="RSA",
        algorithm_family="Public Key Cryptography",
        primitive="asymmetric",
        usage="key_generation",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["RSA factoring is broken by Shor's algorithm on cryptanalytically relevant quantum computers (CRQC)."],
        recommendations=["Migrate to NIST FIPS 204 ML-DSA or FIPS 203 ML-KEM for post-quantum security."],
    ),
    "RSA_generate_key_ex": BinaryCryptoSignature(
        symbol_or_pattern="RSA_generate_key_ex",
        name="OpenSSL RSA Key Generation (Extended)",
        library="OpenSSL",
        algorithm="RSA",
        algorithm_family="Public Key Cryptography",
        primitive="asymmetric",
        usage="key_generation",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["RSA factoring is completely broken by Shor's quantum algorithm."],
        recommendations=["Migrate to ML-KEM for key establishment or ML-DSA for digital signatures."],
    ),
    "RSA_public_encrypt": BinaryCryptoSignature(
        symbol_or_pattern="RSA_public_encrypt",
        name="OpenSSL RSA Public Encryption",
        library="OpenSSL",
        algorithm="RSA",
        algorithm_family="Public Key Cryptography",
        primitive="asymmetric",
        usage="encryption",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["Harvest Now, Decrypt Later (HNDL) risk against RSA encrypted payloads."],
        recommendations=["Transition to FIPS 203 ML-KEM-768 or hybrid post-quantum key encapsulation."],
    ),
    "RSA_private_decrypt": BinaryCryptoSignature(
        symbol_or_pattern="RSA_private_decrypt",
        name="OpenSSL RSA Private Decryption",
        library="OpenSSL",
        algorithm="RSA",
        algorithm_family="Public Key Cryptography",
        primitive="asymmetric",
        usage="encryption",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["RSA private keys are vulnerable to recovery via Shor's algorithm."],
        recommendations=["Upgrade to post-quantum KEMs (ML-KEM)."],
    ),
    "DSA_generate_key": BinaryCryptoSignature(
        symbol_or_pattern="DSA_generate_key",
        name="OpenSSL DSA Key Generation",
        library="OpenSSL",
        algorithm="DSA",
        algorithm_family="Discrete Logarithm",
        primitive="asymmetric",
        usage="key_generation",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=90.0,
        risk_level="CRITICAL",
        vulnerabilities=["DSA is deprecated by NIST and completely broken by Shor's quantum algorithm."],
        recommendations=["Replace immediately with NIST FIPS 204 ML-DSA or stateful hash-based signatures."],
    ),
    "DH_generate_key": BinaryCryptoSignature(
        symbol_or_pattern="DH_generate_key",
        name="OpenSSL Diffie-Hellman Key Generation",
        library="OpenSSL",
        algorithm="Diffie-Hellman",
        algorithm_family="Discrete Logarithm",
        primitive="asymmetric",
        usage="key_exchange",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["Finite-field Diffie-Hellman key exchange is compromised by quantum discrete log attacks."],
        recommendations=["Replace DH with NIST FIPS 203 ML-KEM or hybrid X25519+ML-KEM-768."],
    ),
    "EC_KEY_generate_key": BinaryCryptoSignature(
        symbol_or_pattern="EC_KEY_generate_key",
        name="OpenSSL Elliptic Curve Key Generation",
        library="OpenSSL",
        algorithm="ECDSA/ECDH",
        algorithm_family="Elliptic Curve Cryptography",
        primitive="asymmetric",
        usage="key_generation",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["Elliptic curve cryptography is broken by Shor's algorithm on a CRQC."],
        recommendations=["Plan transition to NIST ML-DSA or ML-KEM."],
    ),
    "ECDSA_sign": BinaryCryptoSignature(
        symbol_or_pattern="ECDSA_sign",
        name="OpenSSL ECDSA Signature",
        library="OpenSSL",
        algorithm="ECDSA",
        algorithm_family="Elliptic Curve Cryptography",
        primitive="asymmetric",
        usage="digital_signature",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=80.0,
        risk_level="HIGH",
        vulnerabilities=["ECDSA signatures can be forged by quantum computers solving the elliptic curve discrete logarithm."],
        recommendations=["Migrate to NIST FIPS 204 ML-DSA or FIPS 205 SLH-DSA."],
    ),
    "ECDH_compute_key": BinaryCryptoSignature(
        symbol_or_pattern="ECDH_compute_key",
        name="OpenSSL ECDH Key Agreement",
        library="OpenSSL",
        algorithm="ECDH",
        algorithm_family="Elliptic Curve Cryptography",
        primitive="asymmetric",
        usage="key_exchange",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["ECDH shared secret derivation is vulnerable to quantum eavesdropping (HNDL)."],
        recommendations=["Adopt hybrid post-quantum key exchange (e.g. X25519Kyber768 / X25519MLKEM768)."],
    ),

    # ── OpenSSL: Symmetric Ciphers ───────────────────────────────────────────
    "EVP_aes_128_gcm": BinaryCryptoSignature(
        symbol_or_pattern="EVP_aes_128_gcm",
        name="OpenSSL AES-128-GCM",
        library="OpenSSL",
        algorithm="AES-128-GCM",
        algorithm_family="AES",
        primitive="symmetric",
        usage="encryption",
        pqc_status="REDUCED_SECURITY_MARGIN",
        quantum_status="reduced_security_margin",
        base_risk_score=40.0,
        risk_level="MEDIUM",
        vulnerabilities=["Grover's algorithm halves effective symmetric key length from 128 to 64 bits."],
        recommendations=["Upgrade to AES-256-GCM for 128-bit post-quantum security margin."],
    ),
    "EVP_aes_256_gcm": BinaryCryptoSignature(
        symbol_or_pattern="EVP_aes_256_gcm",
        name="OpenSSL AES-256-GCM",
        library="OpenSSL",
        algorithm="AES-256-GCM",
        algorithm_family="AES",
        primitive="symmetric",
        usage="encryption",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=10.0,
        risk_level="LOW",
        vulnerabilities=[],
        recommendations=["Maintain current AES-256 configuration."],
    ),
    "EVP_aes_256_cbc": BinaryCryptoSignature(
        symbol_or_pattern="EVP_aes_256_cbc",
        name="OpenSSL AES-256-CBC",
        library="OpenSSL",
        algorithm="AES-256-CBC",
        algorithm_family="AES",
        primitive="symmetric",
        usage="encryption",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=25.0,
        risk_level="LOW",
        vulnerabilities=["CBC mode lacks authenticated encryption (AEAD) and may be vulnerable to padding oracles."],
        recommendations=["Upgrade from CBC mode to an AEAD mode such as AES-256-GCM."],
    ),
    "EVP_chacha20_poly1305": BinaryCryptoSignature(
        symbol_or_pattern="EVP_chacha20_poly1305",
        name="OpenSSL ChaCha20-Poly1305",
        library="OpenSSL",
        algorithm="ChaCha20-Poly1305",
        algorithm_family="Stream Cipher",
        primitive="symmetric",
        usage="encryption",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=10.0,
        risk_level="LOW",
        vulnerabilities=[],
        recommendations=["ChaCha20-Poly1305 has a 256-bit key and is considered quantum resistant."],
    ),
    "DES_set_key": BinaryCryptoSignature(
        symbol_or_pattern="DES_set_key",
        name="OpenSSL DES",
        library="OpenSSL",
        algorithm="DES",
        algorithm_family="Legacy Symmetric",
        primitive="symmetric",
        usage="encryption",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=95.0,
        risk_level="CRITICAL",
        vulnerabilities=["Single DES has 56-bit key size, broken classically and completely insecure."],
        recommendations=["Deprecate DES immediately. Upgrade to AES-256-GCM."],
    ),
    "DES_ede3_cbc_encrypt": BinaryCryptoSignature(
        symbol_or_pattern="DES_ede3_cbc_encrypt",
        name="OpenSSL Triple-DES (3DES)",
        library="OpenSSL",
        algorithm="3DES",
        algorithm_family="Legacy Symmetric",
        primitive="symmetric",
        usage="encryption",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["Sweet32 64-bit block collision vulnerability; deprecated by NIST since 2023."],
        recommendations=["Migrate to AES-256-GCM."],
    ),
    "RC4_set_key": BinaryCryptoSignature(
        symbol_or_pattern="RC4_set_key",
        name="OpenSSL RC4 Stream Cipher",
        library="OpenSSL",
        algorithm="RC4",
        algorithm_family="Legacy Stream Cipher",
        primitive="symmetric",
        usage="encryption",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=95.0,
        risk_level="CRITICAL",
        vulnerabilities=["RC4 contains severe statistical biases and is prohibited in RFC 7465."],
        recommendations=["Prohibit RC4 in all configurations; adopt ChaCha20-Poly1305 or AES-256-GCM."],
    ),

    # ── OpenSSL: Hash Functions ──────────────────────────────────────────────
    "MD5_Init": BinaryCryptoSignature(
        symbol_or_pattern="MD5_Init",
        name="OpenSSL MD5",
        library="OpenSSL",
        algorithm="MD5",
        algorithm_family="Hash",
        primitive="hash",
        usage="hashing",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=95.0,
        risk_level="CRITICAL",
        vulnerabilities=["MD5 is broken by practical classical collision attacks."],
        recommendations=["Replace with SHA-256, SHA-384, or SHA-512."],
    ),
    "SHA1_Init": BinaryCryptoSignature(
        symbol_or_pattern="SHA1_Init",
        name="OpenSSL SHA-1",
        library="OpenSSL",
        algorithm="SHA-1",
        algorithm_family="Hash",
        primitive="hash",
        usage="hashing",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=80.0,
        risk_level="HIGH",
        vulnerabilities=["SHA-1 collision resistance is broken (SHAttered attack)."],
        recommendations=["Migrate to SHA-256 or SHA-3."],
    ),
    "SHA256_Init": BinaryCryptoSignature(
        symbol_or_pattern="SHA256_Init",
        name="OpenSSL SHA-256",
        library="OpenSSL",
        algorithm="SHA-256",
        algorithm_family="SHA-2",
        primitive="hash",
        usage="hashing",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=10.0,
        risk_level="LOW",
        vulnerabilities=[],
        recommendations=["SHA-256 provides 128-bit collision resistance against quantum attacks."],
    ),
    "SHA384_Init": BinaryCryptoSignature(
        symbol_or_pattern="SHA384_Init",
        name="OpenSSL SHA-384",
        library="OpenSSL",
        algorithm="SHA-384",
        algorithm_family="SHA-2",
        primitive="hash",
        usage="hashing",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=5.0,
        risk_level="LOW",
        vulnerabilities=[],
        recommendations=["SHA-384 provides strong quantum collision resistance."],
    ),
    "SHA512_Init": BinaryCryptoSignature(
        symbol_or_pattern="SHA512_Init",
        name="OpenSSL SHA-512",
        library="OpenSSL",
        algorithm="SHA-512",
        algorithm_family="SHA-2",
        primitive="hash",
        usage="hashing",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=5.0,
        risk_level="LOW",
        vulnerabilities=[],
        recommendations=["SHA-512 provides maximum quantum collision resistance."],
    ),

    # ── Post-Quantum Cryptography: liboqs / PQClean / NIST FIPS 203/204/205 ──
    "OQS_KEM_ml_kem_512_new": BinaryCryptoSignature(
        symbol_or_pattern="OQS_KEM_ml_kem_512_new",
        name="liboqs ML-KEM-512 (FIPS 203)",
        library="liboqs",
        algorithm="ML-KEM-512",
        algorithm_family="Lattice-based KEM",
        primitive="pqc",
        usage="key_exchange",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=0.0,
        risk_level="INFO",
        vulnerabilities=[],
        recommendations=["NIST FIPS 203 standardized module lattice post-quantum KEM (Security Category 1)."],
    ),
    "OQS_KEM_ml_kem_768_new": BinaryCryptoSignature(
        symbol_or_pattern="OQS_KEM_ml_kem_768_new",
        name="liboqs ML-KEM-768 (FIPS 203)",
        library="liboqs",
        algorithm="ML-KEM-768",
        algorithm_family="Lattice-based KEM",
        primitive="pqc",
        usage="key_exchange",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=0.0,
        risk_level="INFO",
        vulnerabilities=[],
        recommendations=["Primary NIST FIPS 203 standardized post-quantum KEM (Security Category 3)."],
    ),
    "OQS_KEM_ml_kem_1024_new": BinaryCryptoSignature(
        symbol_or_pattern="OQS_KEM_ml_kem_1024_new",
        name="liboqs ML-KEM-1024 (FIPS 203)",
        library="liboqs",
        algorithm="ML-KEM-1024",
        algorithm_family="Lattice-based KEM",
        primitive="pqc",
        usage="key_exchange",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=0.0,
        risk_level="INFO",
        vulnerabilities=[],
        recommendations=["NIST FIPS 203 standardized post-quantum KEM (Security Category 5)."],
    ),
    "OQS_SIG_ml_dsa_44_new": BinaryCryptoSignature(
        symbol_or_pattern="OQS_SIG_ml_dsa_44_new",
        name="liboqs ML-DSA-44 (FIPS 204)",
        library="liboqs",
        algorithm="ML-DSA-44",
        algorithm_family="Lattice-based Signature",
        primitive="pqc",
        usage="digital_signature",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=0.0,
        risk_level="INFO",
        vulnerabilities=[],
        recommendations=["NIST FIPS 204 standardized post-quantum digital signature algorithm."],
    ),
    "OQS_SIG_ml_dsa_65_new": BinaryCryptoSignature(
        symbol_or_pattern="OQS_SIG_ml_dsa_65_new",
        name="liboqs ML-DSA-65 (FIPS 204)",
        library="liboqs",
        algorithm="ML-DSA-65",
        algorithm_family="Lattice-based Signature",
        primitive="pqc",
        usage="digital_signature",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=0.0,
        risk_level="INFO",
        vulnerabilities=[],
        recommendations=["Primary NIST FIPS 204 standardized post-quantum signature algorithm (Category 3)."],
    ),
    "OQS_SIG_ml_dsa_87_new": BinaryCryptoSignature(
        symbol_or_pattern="OQS_SIG_ml_dsa_87_new",
        name="liboqs ML-DSA-87 (FIPS 204)",
        library="liboqs",
        algorithm="ML-DSA-87",
        algorithm_family="Lattice-based Signature",
        primitive="pqc",
        usage="digital_signature",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=0.0,
        risk_level="INFO",
        vulnerabilities=[],
        recommendations=["NIST FIPS 204 standardized post-quantum signature algorithm (Category 5)."],
    ),
    "OQS_SIG_falcon_512_new": BinaryCryptoSignature(
        symbol_or_pattern="OQS_SIG_falcon_512_new",
        name="liboqs Falcon-512 (FN-DSA)",
        library="liboqs",
        algorithm="Falcon-512",
        algorithm_family="Lattice-based Signature",
        primitive="pqc",
        usage="digital_signature",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=0.0,
        risk_level="INFO",
        vulnerabilities=[],
        recommendations=["NIST selected post-quantum digital signature with compact signature sizes."],
    ),
    "OQS_SIG_sphincs_sha2_128s_new": BinaryCryptoSignature(
        symbol_or_pattern="OQS_SIG_sphincs_sha2_128s_new",
        name="liboqs SLH-DSA / SPHINCS+ (FIPS 205)",
        library="liboqs",
        algorithm="SLH-DSA-SHA2-128s",
        algorithm_family="Stateless Hash-based Signature",
        primitive="pqc",
        usage="digital_signature",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=0.0,
        risk_level="INFO",
        vulnerabilities=[],
        recommendations=["NIST FIPS 205 standardized stateless hash-based signature scheme."],
    ),

    # ── libsodium / NaCl ──────────────────────────────────────────────────────
    "crypto_box_curve25519xsalsa20poly1305": BinaryCryptoSignature(
        symbol_or_pattern="crypto_box_curve25519xsalsa20poly1305",
        name="libsodium crypto_box (Curve25519)",
        library="libsodium",
        algorithm="Curve25519",
        algorithm_family="Elliptic Curve",
        primitive="asymmetric",
        usage="encryption",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=80.0,
        risk_level="HIGH",
        vulnerabilities=["Curve25519 key exchange is vulnerable to Shor's algorithm on a quantum computer."],
        recommendations=["Transition to ML-KEM-768 or hybrid Curve25519+ML-KEM scheme."],
    ),
    "crypto_sign_ed25519": BinaryCryptoSignature(
        symbol_or_pattern="crypto_sign_ed25519",
        name="libsodium crypto_sign (Ed25519)",
        library="libsodium",
        algorithm="Ed25519",
        algorithm_family="Elliptic Curve",
        primitive="asymmetric",
        usage="digital_signature",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=80.0,
        risk_level="HIGH",
        vulnerabilities=["Ed25519 signatures can be broken by quantum discrete logarithm attacks."],
        recommendations=["Adopt ML-DSA-65 or hybrid post-quantum signatures."],
    ),
    "crypto_secretbox_xsalsa20poly1305": BinaryCryptoSignature(
        symbol_or_pattern="crypto_secretbox_xsalsa20poly1305",
        name="libsodium crypto_secretbox (XSalsa20-Poly1305)",
        library="libsodium",
        algorithm="XSalsa20-Poly1305",
        algorithm_family="Stream Cipher",
        primitive="symmetric",
        usage="encryption",
        pqc_status="QUANTUM_SAFE",
        quantum_status="safe",
        base_risk_score=10.0,
        risk_level="LOW",
        vulnerabilities=[],
        recommendations=["Maintain 256-bit symmetric key configuration for quantum safety."],
    ),

    # ── Windows CNG / CryptoAPI ───────────────────────────────────────────────
    "BCryptGenerateKeyPair": BinaryCryptoSignature(
        symbol_or_pattern="BCryptGenerateKeyPair",
        name="Windows CNG Key Pair Generation",
        library="Windows CNG",
        algorithm="RSA/ECC (CNG)",
        algorithm_family="Public Key Cryptography",
        primitive="asymmetric",
        usage="key_generation",
        pqc_status="VULNERABLE",
        quantum_status="vulnerable",
        base_risk_score=85.0,
        risk_level="HIGH",
        vulnerabilities=["Windows CNG default asymmetric key providers rely on RSA or ECC, broken by CRQC."],
        recommendations=["Integrate post-quantum CNG providers or Microsoft SymCrypt with ML-KEM / ML-DSA support."],
    ),
    "BCryptEncrypt": BinaryCryptoSignature(
        symbol_or_pattern="BCryptEncrypt",
        name="Windows CNG Encryption",
        library="Windows CNG",
        algorithm="CNG Cipher",
        algorithm_family="Symmetric / Asymmetric",
        primitive="symmetric",
        usage="encryption",
        pqc_status="UNKNOWN",
        quantum_status="unknown",
        base_risk_score=35.0,
        risk_level="LOW",
        vulnerabilities=["Inspect underlying CNG algorithm handle (BCRYPT_AES_ALGORITHM recommended)."],
        recommendations=["Ensure BCRYPT_CHAIN_MODE_GCM and 256-bit keys are utilized."],
    ),
}

# Prefix patterns for symbol matching (matches functions like EVP_aes_128_gcm_new, etc.)
SYMBOL_PREFIX_RULES = [
    ("EVP_aes_256_", "OpenSSL AES-256", "AES-256", "AES", "symmetric", "QUANTUM_SAFE", "safe", 10.0, "LOW"),
    ("EVP_aes_192_", "OpenSSL AES-192", "AES-192", "AES", "symmetric", "QUANTUM_SAFE", "safe", 20.0, "LOW"),
    ("EVP_aes_128_", "OpenSSL AES-128", "AES-128", "AES", "symmetric", "REDUCED_SECURITY_MARGIN", "reduced_security_margin", 40.0, "MEDIUM"),
    ("EVP_sha3_", "OpenSSL SHA-3", "SHA-3", "SHA-3", "hash", "QUANTUM_SAFE", "safe", 5.0, "LOW"),
    ("EVP_sha512", "OpenSSL SHA-512", "SHA-512", "SHA-2", "hash", "QUANTUM_SAFE", "safe", 5.0, "LOW"),
    ("EVP_sha384", "OpenSSL SHA-384", "SHA-384", "SHA-2", "hash", "QUANTUM_SAFE", "safe", 5.0, "LOW"),
    ("EVP_sha256", "OpenSSL SHA-256", "SHA-256", "SHA-2", "hash", "QUANTUM_SAFE", "safe", 10.0, "LOW"),
    ("EVP_sha1", "OpenSSL SHA-1", "SHA-1", "Hash", "hash", "VULNERABLE", "vulnerable", 80.0, "HIGH"),
    ("EVP_md5", "OpenSSL MD5", "MD5", "Hash", "hash", "VULNERABLE", "vulnerable", 95.0, "CRITICAL"),
    ("OQS_KEM_ml_kem_", "liboqs ML-KEM", "ML-KEM", "Lattice-based KEM", "pqc", "QUANTUM_SAFE", "safe", 0.0, "INFO"),
    ("OQS_KEM_kyber_", "liboqs Kyber (Pre-FIPS)", "Kyber", "Lattice-based KEM", "pqc", "QUANTUM_SAFE", "safe", 5.0, "LOW"),
    ("OQS_SIG_ml_dsa_", "liboqs ML-DSA", "ML-DSA", "Lattice-based Signature", "pqc", "QUANTUM_SAFE", "safe", 0.0, "INFO"),
    ("OQS_SIG_dilithium_", "liboqs Dilithium (Pre-FIPS)", "Dilithium", "Lattice-based Signature", "pqc", "QUANTUM_SAFE", "safe", 5.0, "LOW"),
    ("OQS_SIG_falcon_", "liboqs Falcon", "Falcon", "Lattice-based Signature", "pqc", "QUANTUM_SAFE", "safe", 0.0, "INFO"),
    ("OQS_SIG_sphincs_", "liboqs SPHINCS+", "SPHINCS+", "Hash-based Signature", "pqc", "QUANTUM_SAFE", "safe", 0.0, "INFO"),
    ("mbedtls_rsa_", "mbedTLS RSA", "RSA", "Public Key Cryptography", "asymmetric", "VULNERABLE", "vulnerable", 85.0, "HIGH"),
    ("mbedtls_ecdsa_", "mbedTLS ECDSA", "ECDSA", "Elliptic Curve Cryptography", "asymmetric", "VULNERABLE", "vulnerable", 80.0, "HIGH"),
    ("mbedtls_aes_", "mbedTLS AES", "AES", "AES", "symmetric", "QUANTUM_SAFE", "safe", 20.0, "LOW"),
    ("wc_Rsa", "WolfSSL RSA", "RSA", "Public Key Cryptography", "asymmetric", "VULNERABLE", "vulnerable", 85.0, "HIGH"),
    ("wc_Ecc", "WolfSSL ECC", "ECC", "Elliptic Curve Cryptography", "asymmetric", "VULNERABLE", "vulnerable", 80.0, "HIGH"),
    ("wc_Aes", "WolfSSL AES", "AES", "AES", "symmetric", "QUANTUM_SAFE", "safe", 20.0, "LOW"),
]

# String patterns found embedded in .rodata / binary string tables
STRING_PATTERNS = [
    # OpenSSL banners
    (r"OpenSSL\s+([0-9]+\.[0-9]+\.[0-9]+[a-z]?)", "OpenSSL Library Banner", "OpenSSL", "library"),
    (r"LibreSSL\s+([0-9]+\.[0-9]+\.[0-9]+)", "LibreSSL Library Banner", "LibreSSL", "library"),
    (r"liboqs\s+([0-9]+\.[0-9]+\.[0-9]+)", "liboqs PQC Library", "liboqs", "library"),
    # Quantum-safe algorithms embedded
    (r"(ML-KEM-512|ML-KEM-768|ML-KEM-1024)", "NIST FIPS 203 ML-KEM Identifier", "PQC", "pqc"),
    (r"(ML-DSA-44|ML-DSA-65|ML-DSA-87)", "NIST FIPS 204 ML-DSA Identifier", "PQC", "pqc"),
    (r"(SLH-DSA-SHA2-[0-9]+[sf]|SLH-DSA-SHAKE-[0-9]+[sf])", "NIST FIPS 205 SLH-DSA Identifier", "PQC", "pqc"),
    (r"(Kyber512|Kyber768|Kyber1024)", "Kyber KEM Identifier", "PQC", "pqc"),
    (r"(Dilithium2|Dilithium3|Dilithium5)", "Dilithium Signature Identifier", "PQC", "pqc"),
    (r"(Falcon-512|Falcon-1024)", "Falcon Signature Identifier", "PQC", "pqc"),
    # Classical algorithms embedded
    (r"(RSA-2048|RSA-3072|RSA-4096)", "RSA Key Identifier", "OpenSSL/Crypto", "asymmetric"),
    (r"(secp256r1|prime256v1|secp384r1|secp521r1)", "NIST Elliptic Curve Identifier", "ECC", "asymmetric"),
    (r"(ed25519|curve25519|x25519)", "Bernstein Curve Identifier", "ECC", "asymmetric"),
]
